systemd/dbmail-imapd.service.in, systemd/dbmail-lmtpd.service.in, systemd/dbmail-pop3d.service.in, systemd/dbmail-timsieved.service.in
Inadvertently changed in:
4de4bc5d ("New packaging with systemd", 2017-12-20)
=> Reinstate systemd notify service type

.github/workflows/ccpp.yml, src/dm_misc.c
Added simple compilation workflow
=> SImple Compilation Workflow

acinclude.m4, config.in, configure
Fixing #35  by changing the way headers are detected.
=> Fix jemalloc detection and compilation

contrib/build-rpm/RPM_README
Forgot to include the build guide.
=> Guide for building RPM

src/dm_mailboxstate.c
Fixing group by when building message state.
=> Fixing the grouping query in case of keywords.

dbmail.conf, src/dbmailtypes.h, src/dm_imapsession.c, src/dm_mailboxstate.c, src/dm_message.c, src/dm_misc.c, test/check_dbmail_message.c
potential overflow find_end_of_header (via valgrind)
some comments
fixed test-case timeout.
=> Fix various small bugs and comments

ChangeLog
Change log up-to-date with the future release version
=> Changelog and upgrading

dbmail.conf, src/dm_config.c, src/dm_mailbox.c
Added a switch mailbox_search_strategy which can lower in some situation the database stress. 
More information can be found in dbmail.conf
=> Enhancement mailbox search strategy

src/dm_imapsession.c, src/dm_mailboxstate.h
Added external declaration, fixing #61
=> Enhancement diferential state

dbmail.conf, src/dm_mailboxstate.c
Fix diferential state #68 and some other potential segmentation fault/leakage.
=> Enhancement diferential state 

src/dm_misc.c
=> BSD systems don't use proc

src/dm_mailboxstate.c
=> Fix postgres group concat

src/dm_imapsession.c
=> Fix postgres group missing

dbmail.conf, src/dm_imapsession.c, src/dm_mailboxstate.c, src/dm_mailboxstate.h, src/dm_misc.c
Adding [IMAP]/ mailbox_update_strategy_2_max_iterations which gives the ability to do a full reload after n iterations. It can be beneficial in some setups, mostly multi device over same mailbox and long TTL.
=> Fixing issues related to differential state at the keywords duplication

CHANGELOG.md
=> Small updates to changelog

CHANGELOG.md
=> Change log with the latest fixes.

CHANGELOG.md, dbmail.conf
=> Change log and small typos

sql/mysql/upgrades/32005.mysql
Fixing issue with upgrade scripts (detected on MySQL 8) #93
=> Fix update scripts

sql/postgresql/upgrades/32005.psql
=> update for #97

.travis.yml, Dockerfile
=> Travis Update

debian/changelog
Increased debian minor build number
=> Increased debian minor build number in changelog

INSTALL
=> added missing postgresql installation instructions

compatibility/queue.h, src/dbmail.h.in, src/dm_config.c, src/dm_config.h, src/dm_db.c, src/dm_user.c, src/maintenance.c, src/modules/sortsieve.c
Also checked #106, the format is incorrect, it should be 2 redirects. 
redirect "address1@domain.tld"; 
redirect "address2@domain.tld";
=> Fixed crash on sieve error

CHANGELOG.md, acinclude.m4, configure, make-centos7.sh, make-debian.sh
added also systemd (compatibilization with centos like systems)
=> fix systemd/libsystemd configuration

CHANGELOG.md
=> change log v3.2.6

debian/rules, sql/mysql/create_tables.mariabd
build with `dpkg-buildpackage -uc -us -b`
create_tables compatible with MariadDB 10.6
=> fixes and updates for creating a .deb package

dbmail.conf, src/dm_db.c, src/dm_db.h, src/dm_list.c, src/dm_mailbox.c, src/dm_message.c, src/dm_message.h, src/dm_misc.c, src/dm_tls.c, src/imapcommands.c, src/main.c, src/modules/sortsieve.c
Running locally with no issues
=> Compiler warnings removed and valgrind feedback reduced

src/dm_message.c, src/modules/sortsieve.c, test/check_dbmail.h, test/check_dbmail_deliver.c, test/check_dbmail_imapd.c, test/check_dbmail_mailbox.c, test/check_dbmail_mailboxstate.c, test/check_dbmail_message.c, test/check_dbmail_misc.c, test/check_dbmail_server.c
If date is invalid, then the current date is used instead.
There is still an outstanding issue where appending an incomplete message crashes the server.
=> Gracefully handle invalid dates

contrib/exim-dbmail-configure
and reworking exim-dbmail integration
=> Updated exim-dbmail-configure following updates from exim

systemd/dbmail-timsieved.service.in
Inadvertently deleted in:
34309d42 ("Updated the debian package creation...", 2022-10-28)
=> Restore ExecStart in dbmail-timsieved.service.in

dbmail.conf
Tildslash docs link added to help connection info #200
=> Tildslash docs added to dburi in dbmail.conf

src/authmodule.c
Downgrade failed module loading to DEBUG to fix issue #210
=> Downgrade failed module loading to DEBUG

contrib/build-deb-with-docker.sh
A script to build debian package of dbmail in docker container.
=> Add deb package building script

src/dm_user.c, src/modules/authldap.c
This update caused a bus error elsewhere, reverting until the underlying cause can be found.
=> g_list_free_full reverted

dbmail.conf, man/dbmail.txt
Update
syslog to Emergency + Alert + Critical + Error
file to Emergency + Alert + Critical + Error + Warning
=> Update logging levels to more sensible defaults

docker/Dockerfile, docker/README.md, docker/compose.yaml
Deployments will be easier with docker images, updated for docker-compose #2
This is still considered experimental as forwards, replies, notifies and vacations have not been tested and are unlikely to work.
=> DBMail deployments made easier with docker compose #2

src/dm_mailboxstate.c
keywords free'd in MailboxState_free
=> Fixes tags not saved #238

src/dm_mailboxstate.c, src/dm_mailboxstate.h
=> Refactored fix for #238 Tags not saved

src/dm_message.c
Revert g_object_unref(self->content);
=> Fix memory leak #245

src/dm_dsn.c, src/dm_misc.c
Fixes:
double free dm_misc.c#L2216
sigsegv dm_dsn.c
=> Fix #245 double free and sigsegv

src/dm_message.c, src/dm_misc.c
Also remove inappropriate list-data free
=> Free date_fmt re #245 Memory leak

src/dm_mailboxstate.c, src/dm_message.c, src/dm_misc.c
Free elements in MailboxState_get_set
Free gdt in dbmail_message_set_internal_date
Refactor g_string_split to reduce type conversions
=> Reduce memory leaks re #245

src/dm_dsn.c, src/modules/authldap.c
Also reduce memory leaks in dm_dsn and authldap
=> Fix ldap_memfree #197

src/dm_imapsession.c
When FETCHing header fields all result are returned
This fixes issue #265 header fields returns empty results
=>  Refactor _fetch_headers to fix #265

src/dm_db.c, src/dm_db.h, src/dm_message.c, src/dm_user.c, src/dm_user.h, src/export.c, src/main.c, src/maintenance.c, src/sievecmd.c, src/user.c, test/Makefile.am
with patch from Stefan sthoefer re #284
Also:
Empty envelope check added to util
qerrorf and qprintf refactored
dbmail-util logging refactored
=> Added simple text/plain header when MIME part is invalid #284

dbmail.conf, src/authmodule.c, src/authmodule.h, src/dm_config.c, src/dm_config.h, src/dm_db.c, src/dm_db.h, src/dm_dsn.c, src/dm_dsn.h, src/dm_message.c, src/dm_message.h, src/imapcommands.c, src/lmtp.c, src/maintenance.c, src/modules/authldap.c, src/modules/authsql.c
Part Management
Fix read messages on outlook client related to silent
option to change to utf8mb via maintenanance
=> various patches and options

src/dm_message.c
added a small fix in terms of null in partlist to overcome changes in libzdb in which blob fields with size 0 are converted to null.
=> partlist null workaround

src/dm_message.c
Additional tracing on incoming messages
=> Message init debugging added

src/auth.h, src/modules/authldap.c
Signature for auth_check_user_ext_fw added and
username_from, username_to touched to avoid warnings
=> Warnings fixed for #312

test/check_dbmail_imapd.c, test/check_dbmail_misc.c
strncpy => strlcpy
fail_unless => ck_assert_str_eq
=> Minor changes to tests

src/dm_message.c
When headers are duplicated they can cause errors such as the following:
Error:[message] _header_insert(+1615): SQLException: Duplicate entry '999-1-9999' for key 'dbmail_header.PRIMARY'
This patch checks if the header exists and avoids inserting a duplicate. The select count(*) is efficient as it uses the primary key.
=> Avoid inserting headers twice

src/maintenance.c, src/user.c
Also reword a comment in user.c
=> Refactor if statements into blocks

docker/Dockerfile-amd64-ubuntu-350, docker/Dockerfile-amd64-ubuntu-devel, docker/README.md
=> Dockerfiles added for Ubuntu development and v3.5

src/dm_iconv.c, test/check_dbmail_imapd.c
test_dm_base_subject_misc4 and test_dm_base_subject_utf8 regenerated
=> dbmail_iconv_decode_text and address reworked

src/clientbase.c, src/dm_db.c
Retry interval was too short and swamped both logs and cpu
Reducing to 0.1 second
=> SSL Retry interval bumped to 0.1 second

CHANGELOG.md, dbmail.conf, src/dm_config.c, src/dm_debug.c, src/dm_message.c, src/dm_user.h, src/export.c, src/maintenance.c, src/server.c, src/user.c
Logging has been refactored so there is only one log file configured with logfile.
CLI utilities logging identifier updated to reflect their names
CLI user output and logging improved
CLI utilities respect their entries in dbmail.conf
=> Logging refactored

src/dm_message.c
Null dates 1970-01-01 00:00:00 should be accepted
=> Assert replaced by default date

dbmail.conf
as per section 1.8 Transport in rfc5804
=> dbmail-sieved should listen on port 4190

src/dm_misc.c
https://dbmail.org/wws/arc/dbmail-general/2025-06/msg00009.html
=> Test failure fixed thanks to Tom Ivar Helbekkmo

test-scripts/7bitmime.lmtp, test-scripts/8bitmime.lmtp, test-scripts/README.md, test-scripts/check.sh, test-scripts/smtputf8.lmtp, test/README.md
check.sh script added
checks for SMTPUTF8 and {7,8}BITMIME
README for test and test-scripts
=> Integration test script added
