acinclude.m4

There was a mistake in c6773f6 that I missed.
A copy of https://github.com/pjstevns/dbmail/pull/45

fix detection of systemd libs on systemd >= 230

---

src/clientbase.c

Set client_state CLIENT_ERR if connection was closed from client side.
This is bug fix for the problem which described [here](http://dbmail.org/mantis/view.php?id=1029)
Also works for 3.1.7 release.
Python script for test:
> REQUESTS_COUNT must be more than 'Max open files' for process 
> see here: /proc/(PID dbmail-imapd)/limits
```
#!/usr/bin/env python3
import socket
import time
HOST = WRITE_YOUR_HOST
PORT = 143
USER_LOGIN = 'testlogin'
USER_PASSWORD = 'testpwd'
IMAP_LOGIN_REQUEST = '. login {} {}\n'.format(USER_LOGIN, USER_PASSWORD).encode()
REQUESTS_COUNT = 2000
for _ in range(REQUESTS_COUNT):
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
s.connect((HOST, PORT))
data = s.recv(4096)
s.sendall(IMAP_LOGIN_REQUEST)
if b"* BYE [Service unavailable.]" in data:
print('Service …
```

Fix fd leaks in clientbase

---

src/dm_db.c

Closes: http://www.dbmail.org/mantis/view.php?id=884
---
Uses server_conf which may be available in dm_db.c. It is therefore not so good for e.g. dbmail-util or dbmail-deliver which will all show as dbmail_client. This could be fixed with a new extern?
No API change means doesn't impact the existing tests.
I think by now no need to check for libzdb >= 2.8. Debian stable has 3.1. If needed maybe PR https://github.com/pjstevns/dbmail/pull/25 could be the solution.
Copied from https://github.com/pjstevns/dbmail/pull/39

support PostgreSQL application_name

---

src/imapcommands.c

Response in MODIFIED keyword has wrong parameter(s) format.

According to RFC7162 section 3.1.3.0 MODIFIED keyword should be used

---

src/imapcommands.c

According to RFC7162 section 3.1.3.0 MODIFIED keyword should be used as response like 
as response like "... OK [MODIFIED x,y] ..." not "...OK [MODIFIED [x,y]]..."
Some clients cannot deal with double [ Modified [ ]] annotation.

RFC7162 section 3.1.3.0 MODIFIED keyword issue

---

src/imap4.c

[RFC3501](https://tools.ietf.org/html/rfc3501)  states that the correct format is `* OK [optional message]`, but some clients do consider message mandatory.

Fix ok still here

---

README.md
src/imap4.c

Some clients does not handle “* OK” but do “* OK message” (although in RFC 3501 is only optional, some clients may require it)

Fix “* OK Still here”

---

src/dm_misc.c

In some cases this function can buffer overflow. Also some hard limits were imposed, more information #22

Fix imap append hash as string #22

---

README.md
src/dm_misc.c

Fixing buffer overflow (in some OS-es the possibility is higher due to the state of memory). Also added hard limits to the same buffers, as specified by the definition of fields.  
it refers to #12  (https://github.com/dbmail/dbmail/issues/12)

Fix imap append hash as string

---

src/dbmailtypes.h
src/dm_db.c
src/dm_imapsession.c
src/dm_mailbox.c
src/dm_mailboxstate.c

Evaluating the way initial states are build, it can be optimized either by using pure sql or some small coding workarounds: 
- load state will include only valid messages (state=0 and state=1), old version did include all
- keywords sql was optimized in order to limit internal tree search 
- for the readability most of the queries that were related to status ware changed to include status<MESSAGE_STATUS_DELETED and not status in (MESSAGE_STATUS_NEW,MESSAGE_STATUS_SEEN) 
- optimized the way phymessage_id is retrieved from database, offloading the db
- optimized header retrieving sql in order to offload the database
Some of the related information can be found in #47

optimizations SQL in some code update

---

src/imap4.c

Fix BYE command
Some clients do not accept missing message on BYE command (e.g. Outlook 2016). Even [RFC3501 ](https://tools.ietf.org/html/rfc3501#page-67) does not require a message, given the situation it is best to provide it.

Fix bye command

---

src/dm_misc.c

Fixing bodystructure format. some information got missed upon processing header.  The fixing #12  introduced the omission of last character. So we kept the fix with a minor modification.
it fixes #49

Fix bodystructure format

---

src/dm_mailbox.c
src/dm_string.c

Given the fact that at select folder level a state of the folder is created, some of the searches can be done using this state, alleviating the db stress. 
So where implemented the following searches: 
- internal_date >,<,= ?
- answered_flag=1
- deleted_flag=1
- flagged_flag=1  
- recent_flag=1
- seen_flag=1
- draft_flag=1
- (seen_flag=0 AND recent_flag=1)
- recent_flag=0
- answered_flag=0
- deleted_flag=0
- flagged_flag=0
- seen_flag=0
- draft_flag=0
Alt the conditions above gets matched to search imap options

Optimizations, search parameters, IMAP

---

dbmail.conf
src/dbmailtypes.h
src/dm_imapsession.c
src/dm_mailboxstate.c

DBMail creates a state of the current folder and each sequential change does reissue this changes which, in some context, can stress the backend DB. 
So, a switch in configuration was proposed to use this differential state update.

Enhancement differential state

---

src/dm_tls.c

.libs/libdbmail_la-dm_tls.o:(.bss+0x0): multiple definition of `tls_context';
.libs/libdbmail_la-server.o:(.bss+0x40): first defined here

Fix building with GCC 10 / -fno-common

---

src/imapcommands.c

Fixing #87 by adding some checks and invalidating response in failing copying message due to internal issues (RFC 3501, section 6.48. does stat that the copy message should

Fix copymsg

---

sql/mysql/2_2_5-2_3_0.mysql
sql/mysql/create_tables.mysql
sql/mysql/migrate_from_1.x_to_2.0_innodb.mysql
sql/mysql/migrate_from_2.0_to_2.2.mysql

For https://github.com/dbmail/dbmail/issues/99
Mysql 8.x changed the minimum datetime value to 1000-01-01. Thus commit changes entries using 0000-00-00 for datetime under /sql/mysql
On a side note, I noticed some defaults are epoch time (1970-01-01), and others were 0000-00-00.. not sure if there is a reason for the difference or if it even poses an issue (totally new to dbmail)

Fix for mysql 8.x datetime default value

---

src/dm_db.c

I tried to run dbmail-httpd and got this log:
```
Sep 30 16:53:44 04dcede84c4b dbmail-httpd[13330]: [0x555c221b3800] Notice:[server] server_run(+770): starting main service loop for [HTTP]
Sep 30 16:53:44 04dcede84c4b dbmail-httpd[13330]: [0x555c221b3800] Debug:[db] db_connect(+213): dburi: sqlite:///tmp/dbmail.db?application-name=dbmail-httpd
Sep 30 16:53:44 04dcede84c4b dbmail-httpd[13330]: [0x555c221b3800] Database:[db] db_connect(+261): db at dburi: [sqlite:///tmp/dbmail.db?application-name=dbmail-httpd]
Sep 30 16:53:44 04dcede84c4b dbmail-httpd[13330]: [0x555c221b3800] Info:[db] db_connect(+271): database connection pool created with maximum connections of [10]
Sep 30 16:53:44 04dcede84c4b dbmail-httpd[13330]: [0x555c221b3800] Database:[db] db_connect(+275): run a database connection …
```

Only add application-name to postgresql dburi

---

src/dm_mailbox.c
src/dm_mailbox.h
src/imapcommands.c

Fixes #111 wrong sql by seperating dbmail_mailbox_ids_as_string
into dbmail_mailbox_imap_modseq_as_string for sorted_search_enter in imapcommands.c

Fixes #111 wrong sql

---

src/dm_message.c
src/modules/authsql.c

Added fixes for #122 and checked #134 
#122
- although the contributor provided a solution, that breaks the architecture, the checks should be made in authsql.c
#134
- checked, the issue arises from duplicate headers, but by design, the app, makes a rollback, but from some reason that does not happen in postgres, maybe due to libzdb.

Fix #122, checks #134

---

src/dm_db.c

2-byte salt was breaking $id$salt$ prefixes in crypt().
Using the whole encrypted string as it's own salt works the same as passing only the salt in crypt()'s second parameter.

Support $id$ additional encryption algorithms

---

src/dm_message.c

Leading trailing spaces removal moved to dbmail_message_cache_headers to avoid memory corruption

Move trimming to dbmail_message_cache_headers

---

AUTHORS
README.md
THANKS
UPGRADING
dbmail.conf

Log and PID files should by default live in their respective dbmail directories
/var/log/dbmail/ and /var/run/dbmail/
as identified by BobRam in #170

Log and pid directories appended with dbmail

---

debian/patches/series
debian/patches/systemd_mkdir
systemd/Makefile.am
systemd/Makefile.in

05545ee breaks non-Debian installation of systemd units when using DESTDIR. Revert that and add a patch for Debian.

Fix systemd directory creation

---

contrib/exim-dbmail-configure
doc/README.exim

Exim 4.93 Introduced a tainting mechanism for values read from untrusted sources.
As of 4.96 it is no longer possible to rely on local_part and domain in a received email as they are considered tainted and the option allow_insecure_tainted_data has been removed. Both the local_part and domain must be checked before they can be used and after a successful match are available in $local_part_data and $domain_data.
This update follows the spirit of checking tainted data against either sql or ldap.
With the sql authdriver it's easy to check both local_part and domain as that information is easily accessible in the dbmail_alias table.
If the ldap driver is used solely for authentication, then using the sql alias table is the recommended option.
If aliases are searched using the ldap mail …

Fix issue #194 by de-tainting local_part and domain

---

src/dm_message.c
src/maintenance.c

The default was no and has been changed to yes to reflect dbmail.conf #206

header_cache_readonly default set to yes

---

src/dbmail.h.in
src/dm_message.c

Headers are duplicated for any number of reasons, when failing to add a duplicate to dbmail_header these should be reduced to a warning instead of an error.

Duplicate headers reduced to warning

---

man/dbmail-util.txt
src/maintenance.c

As upgrades are handled automatically, deprecated dbmail-util -u should no longer appear in the help or man page.

Remove deprecated -u from dbmail-util man page

---

make-debian.sh

make-debian.sh fails to install libsieve if the CPU architecture of the server is arm64...due to config.guess: 
`configure: error: cannot guess build type; you must specify one`
A workaround is to use **./configure --build=unknown-unknown-linux** instead of ./configure.
I've added a check to see if the CPU architecture is aarch64 using **uname -m**.

make-debian.sh fails on arm64

---

src/export.c
src/main.c
src/maintenance.c
src/server.c
src/sievecmd.c
src/user.c

Distributions can change the default configuration file.
Help (-h) shows the default config file location.

Default config file added to help

---

src/dm_db.c
src/dm_db.h

A few core headers are required in dbmail_headername, this checks and adds any missing.

Check core headernames

---

src/dm_mailboxstate.c

Building DBMail 3.4.1 with gcc 14.1.1 fails with compiler error
dm_mailboxstate.c:646:64: error: passing argument 3 of ‘g_list_find_custom’ from incompatible pointer type ...                      
Building against GLib 2.80.0, though neither GLib nor DBMail has changed anything surrounding this code since forever.  Evidently gcc has gotten more strict.
The offending pointer is to function (src/dm_misc.c:) dm_strcmpdata, which does double duty as type GCompareFunc and GCompareDataFunc.  the only difference being that the latter signature has an extra argument.  The implementation of dm_strcmpdata does not use the extra argument and declares it UNUSED.
Fixed by casting to the type expected by g_list_custom; safe per the preceding remarks.

Fix 'incompatible pointer type' compiler error

---

src/dm_db.c

In imapcommands.c(1733) db_set_msgflag is called with msginfo=NULL
If msginfo is not set it returns 0.

Fix for sig11 null reference

---

dbmail.conf
src/dm_message.c

There are rare occasions, for example upgrading an old 2.2 version where dbmail should process and accept invalid emails. Setting allow_invalid_messages = yes will add a mime header allowing dbmail to store an invalid message.

Allow dbmail to accept invalid messages

---

src/dm_db.c

Select statement not allowed in PreparedStatement_execute()

Fix for SQLException #305

---

src/dm_db.c
src/dm_db.h

If a sequence is supplied to db_set_msgflag() it should only be used as a filter.
This patch restores the sequence filter and removes setting it.
Redundant db_mailbox_seq_get removed

db_set_msgflag sets flags but shouldn't set seq fixes #314

---

src/dbmailtypes.h
src/dm_db.c
src/dm_mailboxstate.c
src/dm_misc.c
test/check_dbmail.h
test/check_dbmail_common.c
test/check_dbmail_imapd.c
test/check_dbmail_mailbox.c
test/check_dbmail_mailboxstate.c
test/check_dbmail_message.c

The upgrade to gmime version 3 was implemented at pace to ensure dbmail continued after the removal of version 2. These patches finish the upgrade and all tests now pass.
GMime improves message processing so there are a number of changes including mime examples amended to fix errors and omissions where appropriate. Output is now utf-8 so the expected output is amended where necessary. The latest version of check introduced new macros to make testing easier and  ck_assert_str_eq replaces COMPARE.
There is a bug in how multipart_digest is processed and a separate issue has been raised #324.
Although passing, these tests should probably be refactored for consistency.

Complete upgrade to gmime3

---

src/dm_message.c

Envelope caching can have failed duplicate inserts, these create noise rather than indicate an error and this patch reduces them to warnings. Part of #333

Duplicate envelope inserts now treated as warnings

---

contrib/build-centos-rpm/dbmail.spec
contrib/build-centos-rpm/libsieve.spec
contrib/build-centos-rpm/libzdb.spec

Changes made to RPM spec files:
dbmail.spec:
- Update version to 3.5.0
- Update source URL to use GitHub main branch
- Fix source directory path for main branch
- Comment out deprecated gmime patch
libsieve.spec:
- Update version to 2.2
- Update source URL to use GitHub archive
- Fix source directory path for archive structure 
- Update build process to use bootstrap script
- Fix documentation path
libzdb.spec:
- Update version to 3.4.0
- Update source URL to use tildeslash.com
- Add autoconf-archive build dependency
- Remove manual libtoolize/autoreconf steps
All changes tested and verified to build successfully.

Update RPM spec files for dbmail, libsieve and libzdb

---

test/check_dbmail_imapd.c

The test has two mime encoded strings, separator updated to \n

Test hello from russia updated to be rfc2046 compatible

---

src/dm_db.c

Encoding was ambiguous, declaring it as client avoids confusion.

Client encoding clarified

---

src/dm_mailboxstate.c

Confusing text "Aii" in trace message adds no value and should be removed.

Errant Aii string removed from trace

---

dbmail.conf

20 Oct 2015 — DSS (DSA) keys were phased out from the major browsers.

Key formats are now ECDSA or RSA

---

dbmail.conf

Sieve notify is not supported by the sortsieve utility in src/modules/sortsieve.c, so turn it off by default in dbmail.conf.

Turn off unsupported sieve_notify option by default

---

src/dm_debug.c

I was too quick with #451 -- TRACE() can be called at times when it's not possible to check config file values; notably during exit(), from handlers installed with atexit(). This leads to crashes.
However, the variable fstderr is initialized to NULL, and then set (from an freopen() call) if and only if the value of the paramer "logfile" is something other than "stderr", so it can be used to check for this instead.

Allow TRACE() to be used after config resources have been freed

---

src/dm_imapsession.c
src/export.c
src/imap4.c
src/imapcommands.c

I've just had to debug connection establishment problems for an IMAP client. Having the session ID included in all relevant log lines is very important when you're studying a single connection among many. This patch fixes the relatively few occurrences of TRACE calls at non-DEBUG levels in IMAP code that were missing this information.
Additionally, a TRACE call is added, in imap4.c, to log, with session ID, the establishment of a new session. This is done to document the session ID of the new connection as early as possible, making it easy to extract from the log all lines relevant to a particular session, by searching for the ID.
While here, fix the wording of the "quota exceeded" error situation. :)

Make imapd log lines consistently include the session identifier

---

contrib/startup-scripts/netbsd/dbmail_httpd
contrib/startup-scripts/netbsd/dbmail_imapd
contrib/startup-scripts/netbsd/dbmail_lmtpd
contrib/startup-scripts/netbsd/dbmail_pop3d
contrib/startup-scripts/netbsd/dbmail_sieved
src/dbmail.h.in

NetBSD has a <sys/featuretest.h> that is included by everything that needs it, and that does not require any definition of _XOPEN_SOURCE to enable the features that dbmail needs.
The sample startup scripts added may be dropped into the directory /etc/rc.local.d/, and configured in /etc/rc.conf in the usual manner.

Allow building on NetBSD and add sample startup scripts.

---

src/dm_imapsession.c

As pointed out by alan-hicks in #468, I introduced a couple of conversion warnings. This makes those (desired) conversions explicit.

Get rid of a couple of warnings introduced in PR#468

---

src/dm_imapsession.c

This lets a client specify all three fields of the authentication data structure if the username to authenticate as and the username whose rights are wanted are the same.  This is allowed per the RFC, and we want to be sure we accept clients that do it.

Allow "no-op" proxy authentication in AUTHENTICATE PLAIN.

---

src/dm_imapsession.c
src/dm_imapsession.h
src/imap4.c
src/imapcommands.c

The separation into the two capability maps is improved, by letting a session have exactly the capabilities, in each of them, that it's allowed to use during the pre- and post-authentication phases.  While 'capa' does not change after session initialization, 'preauth_capa' may change during the pre-authentication phase, for instance when a plaintext session successfully uses STARTTLS to enable encryption.
The initial setup of capabilities in dbmail_imap_session_new() is simplified somewhat by this change.
Capability manipulation is isolated to dm_imapsession.c, by adding a function dbmail_imap_session_encrypted(), that is called if the session successfully does a STARTTLS, or if it uses TLS to begin with.
The CAPABILITY command now returns the correct capability set for the current …

Clean up usage of 'preauth_capa' and 'capa'.

---

src/dm_imapsession.c
src/dm_message.c
src/dm_misc.c

From the Linux ctype man page:
The standards require that the argument c for these functions is
either EOF or a value that is representable in the type unsigned
char. If the argument c is of type char, it must be cast to unsigned
char, as in the following example: [...]
From the NetBSD ctype man page:
The argument of these functions is of type int, but only a very
restricted subset of values are actually valid.  The argument must
either be the value of the macro EOF (which has a negative value), or
must be a non-negative value within the range representable as
unsigned char.  Passing invalid values leads to undefined behavior.

The ctype functions need unsigned char arguments, so cast as appropriate.
